# Minimal configuration

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
bootstrap = {}
drivers = {}
ipcd = {}
kernel = {}
# TODO: Should the minimal conf have escalated?
escalated = {}
ptyd = {}

# User settings
[users.root]
password = "password"
uid = 0
gid = 0
name = "root"
home = "/root"

[users.user]
# Password is unset
password = ""

[[files]]
path = "/etc/init.d/00_base"
data = """
ipcd
ptyd
pcid /etc/pcid.d/
escalated
"""

[[files]]
path = "/usr/bin"
data = "../bin"
symlink = true

[[files]]
path = "/usr/games"
data = "../games"
symlink = true

[[files]]
path = "/usr/include"
data = "../include"
symlink = true

[[files]]
path = "/usr/lib"
data = "../lib"
symlink = true

[[files]]
path = "/usr/share"
data = "../share"
symlink = true

[[files]]
path = "/tmp"
data = ""
directory= true
# 0o1777
mode = 1023
